### ISSUE TITLE
Unable to find plugin

### ISSUE THREAD

**Issue by ThePeach** [mojodna/gatsby-remark-copy-images#2]
Hello, I'm trying to use the plugin so I've followed the instructions with:

    npm install --save gatsby-remark-copy-images

and added the following to `gatsby-config.js`:

    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          'gatsby-remark-autolink-headers',
          'gatsby-remark-copy-images'
        ]
      }
    },

but when running gatsby I get the following error:

```
success open and validate gatsby-config.js — 0.006 s
error UNHANDLED REJECTION


  Error: Unable to find plugin "gatsby-remark-copy-images"

  - load-plugins.js:96 resolvePlugin
    [project]/[gatsby]/dist/bootstrap/load-plugins.js:96:11

  - load-plugins.js:118 processPlugin
    [project]/[gatsby]/dist/bootstrap/load-plugins.js:118:26

  - load-plugins.js:130
    [project]/[gatsby]/dist/bootstrap/load-plugins.js:130:35

  - Array.forEach

  - load-plugins.js:129 processPlugin
    [project]/[gatsby]/dist/bootstrap/load-plugins.js:129:40

  - load-plugins.js:168
    [project]/[gatsby]/dist/bootstrap/load-plugins.js:168:28

  - Array.forEach

  - load-plugins.js:167 _callee$
    [project]/[gatsby]/dist/bootstrap/load-plugins.js:167:28

  - index.js:122 _callee$
    [project]/[gatsby]/dist/bootstrap/index.js:122:20
```

I'm using node 6.7.0 (latest version I can install unfortunately)
and npm 3.10.3
with gatsby 1.9.32

**Comment by t4t5** [comment]
Same problem here.

**Comment by againer** [comment]
Same same.

**Comment by sethfitz** [comment]
[v0.2.0 is published on npm](https://www.npmjs.com/package/gatsby-remark-copy-images); can you confirm that it's present in your `node_modules/` directory?

**Comment by sethfitz** [comment]
Fixed by #3 and published as v0.2.1 -- thanks @joyhchen!!

**Comment by ngminhtrung** [comment]
I encountered the same issue today. 

```js
// package.json
"gatsby-remark-copy-images": "^0.2.1",
```
Error: Unable to find plugin "gastby-remark-copy-images"`

**Comment by ruden91** [comment]
delete node_modules & package.lock.json and npm install (yarn install)
